### ISSUE TITLE
Initial data not loading for transaction table

### ISSUE THREAD

**Issue by Clavvv** [Clavvv/OnlineMarketplace#17]
We should add the data for completed listings into the transactions table

**Comment by brandonpham13** [comment]
completed transaction/listings interaction. adding a new transaction now gives users option to only select from existing listings. (it might be a good idea to further filter selectable listings only from those that the status are active or whatever)

adding a new transaction now changes the listing status to sold.

**Comment by brandonpham13** [comment]
should deleting a transaction re-open a listing??
